Squashed commit of the following:
commit 22ad92f1cd6e89de5c8e7b0cb4fe4940c936f966
Author: SGrottel <sgrottel@sgrottel.de>
Date:   Thu May 4 14:01:05 2023 +0200

    Add `readme` tag to nuspec

commit 5c86ae0dc93ea4a5cdf067b10d79ae9217ab9d5a
Author: SGrottel <sgrottel@sgrottel.de>
Date:   Thu May 4 13:30:34 2023 +0200

    Corrected test executable search path

commit 57446a1f7aed2990d1c6e612358e8e843b9a6dac
Author: SGrottel <sgrottel@sgrottel.de>
Date:   Thu May 4 13:02:58 2023 +0200

    Build and run `TestNuget`

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -154,17 +154,43 @@ jobs:
     - name: Add MSBuild to PATH
       uses: microsoft/setup-msbuild@v1.1
 
-    - name: Build NuGet
+    - name: Build NuGet Package
       shell: pwsh
       run: |
         $packageVersion = 2
         .\makeNuget.ps1 $packageVersion
 
-    - name: Build TestPackage
-      run: cd .
+    - name: Prepare TestNuget
+      working-directory: ./testnuget
+      shell: pwsh
+      run: |
+        .\prepareProject.ps1
+        nuget restore
 
-    - name: Run TestPackage
-      run: cd .
+    - name: Build TestNuget x64 Release
+      working-directory: ./testnuget
+      run: msbuild /m /p:Configuration=Release /p:Platform=x64 .
+    - name: Build TestNuget x64 Debug
+      working-directory: ./testnuget
+      run: msbuild /m /p:Configuration=Debug /p:Platform=x64 .
+    - name: Build TestNuget x86 Release
+      working-directory: ./testnuget
+      run: msbuild /m /p:Configuration=Release /p:Platform=x86 .
+    - name: Build TestNuget x86 Debug
+      working-directory: ./testnuget
+      run: msbuild /m /p:Configuration=Debug /p:Platform=x86 .
+
+    - name: Run TestNuget
+      shell: pwsh
+      working-directory: ./testnuget
+      run: |
+        $tests = (gci -recurse -path . -include TestNuget.exe)
+        if ($tests.Length -ne 4)
+        {
+          Write-Error "TestNuget.exe not found"
+          exit 1
+        }
+        $tests | foreach { & $_ }
 
     - uses: actions/upload-artifact@v3
       with:
