Building and running TestBuild.exe
Expecting error because script file will not be found (wrong working directory for test execution)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -14,28 +14,28 @@ jobs:
       fail-fast: true
       matrix:
         toolConfig:
-        - {
-            toolset: v120,
-            winTarget: '10.0',
-            vs2022addMod: ''
-          }
-        - {
-            toolset: v140,
-            winTarget: '10.0.19041.0',
-            vs2022addMod: 'Microsoft.VisualStudio.Component.VC.140'
-          }
-        - {
-            toolset: v141,
-            winTarget: '10.0.19041.0',
-            # Already available on runner
-            # vs2022addMod: 'Microsoft.VisualStudio.Component.VC.v141.x86.x64'
-          }
-        - {
-            toolset: v142,
-            winTarget: '10.0',
-            # Already available on runner
-            # vs2022addMod: 'Microsoft.VisualStudio.Component.VC.14.29.16.11.x86.x64'
-          }
+        # - {
+        #     toolset: v120,
+        #     winTarget: '10.0',
+        #     vs2022addMod: ''
+        #   }
+        # - {
+        #     toolset: v140,
+        #     winTarget: '10.0.19041.0',
+        #     vs2022addMod: 'Microsoft.VisualStudio.Component.VC.140'
+        #   }
+        # - {
+        #     toolset: v141,
+        #     winTarget: '10.0.19041.0',
+        #     # Already available on runner
+        #     # vs2022addMod: 'Microsoft.VisualStudio.Component.VC.v141.x86.x64'
+        #   }
+        # - {
+        #     toolset: v142,
+        #     winTarget: '10.0',
+        #     # Already available on runner
+        #     # vs2022addMod: 'Microsoft.VisualStudio.Component.VC.14.29.16.11.x86.x64'
+        #   }
         - {
             toolset: v143,
             winTarget: '10.0',
@@ -119,6 +119,18 @@ jobs:
     - name: Build x86 Debug
       working-directory: ${{env.GITHUB_WORKSPACE}}
       run: msbuild /m /p:Configuration=Debug /p:Platform=x86 .
+
+    - name: Run TestBuild
+      shell: pwsh
+      working-directory: ${{env.GITHUB_WORKSPACE}}
+      run: |
+        $tests = (gci -recurse TestBuild.exe)
+        if ($tests.Length -ne 4)
+        {
+          Write-Error "TestBuild.exe not found"
+          exit 1
+        }
+        $tests | foreach { & $_ }
 
     - uses: actions/upload-artifact@v3
       with:
