Test build (#6)
* Building and running TestBuild.exe

Expecting error because script file will not be found (wrong working directory for test execution)

* Correct test directory should run green now

* Trying to fix working directory syntax

* Enabling all build targets again

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -120,6 +120,18 @@ jobs:
       working-directory: ${{env.GITHUB_WORKSPACE}}
       run: msbuild /m /p:Configuration=Debug /p:Platform=x86 .
 
+    - name: Run TestBuild
+      shell: pwsh
+      working-directory: ./testbuild
+      run: |
+        $tests = (gci -recurse -path ..\bin -include TestBuild.exe)
+        if ($tests.Length -ne 4)
+        {
+          Write-Error "TestBuild.exe not found"
+          exit 1
+        }
+        $tests | foreach { & $_ }
+
     - uses: actions/upload-artifact@v3
       with:
         name: lua-bin
@@ -137,6 +149,7 @@ jobs:
     - uses: actions/download-artifact@v3
       with:
         name: lua-bin
+        path: bin
 
     - name: Show me what you got
       shell: pwsh
